query Page($slug: String!) {
  page(where: { slug: $slug }) {
    slug
    ogTitle
    ogDescription
    ogImage
    navigationLabel
    blocks {
      ... on Copy {
        id
        componentName
        space
        copy {
          html
        }
      }
      ... on SingleImage {
        id
        componentName
        cloudinaryImage
        space
      }
      ... on TwoColumn {
        id
        space
        title
        componentName
        sideA {
          ... on Copy {
            id
            componentName
            copy {
              html
            }
            space
          }
          ... on SingleImage {
            id
            cloudinaryImage
            componentName
            space
          }
        }
        sideB {
          ... on Copy {
            id
            componentName
            copy {
              html
            }
            space
          }
          ... on SingleImage {
            id
            cloudinaryImage
            componentName
            space
          }
        }
      }
    }
  }
}
